bsys/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

## TODO: add permissions to the crud form pages to prevent drivers from modifing other drivers/users data
app_name = 'bsys'
urlpatterns = [
    path("",views.index,name ='index'),
    path("home/",views.home,name ='home'),
    path('profile/b/delete/<int:pk>',login_required(views.BusDeleteView.as_view()), name='BusDelete'),
    path('profile/d/delete/<int:pk>', login_required(views.DriverDeleteView.as_view()), name='DriverDelete'),
    # path("signup/",views.sign_up,name ='signup'),
    path('profile/b/edit/<int:pk>', login_required(views.BusUpdate.as_view()), name='BusEdit'),
    path('profile/dp/edit/<int:pk>', login_required(views.DriverUpdatePersonal.as_view()), name='DriverPersonalEdit'),
    path('profile/d/edit/<int:pk>', login_required(views.DriverUpdate.as_view()), name='DriverEdit'),
    path('profile/b/list/', login_required(views.BusList.as_view()), name='BusList'),
    path('profile/d/list/', login_required(views.DriverList.as_view()), name='DriverList'),
    path('signup/', login_required(views.DriverSignUpView.as_view()), name='signup'),
    path("success/",views.success_test,name ='success'),
    path("faliur/",views.faliur_test,name ='faliur'),
    path("logout/",views.logout_view,name="logout"),
    path("profile/",views.profile,name="profile"),
    path('profile/d/create/', login_required(views.DriverSignUpFormView.as_view()), name='driverCreate'),
    path('profile/b/create/', views.BusCreationFormView, name='BusCreate'),
    path('profile/b/update/', views.BusUpdateView, name='BusUpdate'),
]

bus_system/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

bsys/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser , BaseUserManager
# from django.contrib.auth.models import User
from django.db import transaction

# Create your models here.

# class CustomUser(AbstractUser):
#     pass

# class Role(models.Model):
#     ROLE_CHOICES = (
#         (1, 'Driver'),
#         (2, 'Admin'),
#     )
#     # id = models.IntegerField(primary_key=True)
#     name = models.CharField(choices=ROLE_CHOICES,max_length=12)
#     def __str__(self):
#         return self.get_id_display()

class User(AbstractUser):
    # roles = models.ForeignKey(
    #     'Role',
    #     on_delete=models.CASCADE,
    #     # null= True
    # )
    is_admin = models.BooleanField("admin status",default=False)
    is_driver = models.BooleanField("driver status",default=False)
    salary = models.FloatField("salary",default=2000)


class Manager(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    def __init__(self, *args, **kwargs):
        # self._meta.   get_field('is_admin').default = True
        super(Manager, self).__init__(*args, **kwargs)


class Bus(models.Model):
    """docstring for ."""
    licenceCode = models.CharField(max_length=20,null=True)
    status = models.BooleanField("status",default=False)
    lastCheckUp = models.DateField(null=True)
    def __str__(self):
        return self.licenceCode

class Driver(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    bus = models.OneToOneField(Bus ,null=True,on_delete=models.SET_NULL)
    licenceNum = models.CharField(max_length=20,null=True)
    def __str__(self):
        return self.user.first_name
    def __init__(self, *args, **kwargs):
        # self._meta.get_field('is_driver').default = True
        super(Driver, self).__init__(*args, **kwargs)

class RoadLines(models.Model):
    """docstring for ."""

    # def __init__(self, arg):
    #     super(, self).__init__()
    #     self.arg = arg
    pass

class StopStations(models.Model):
    pass

class Areas(models.Model):
    """docstring for areas."""

    # def __init__(self, arg):
    #     super(areas, self).__init__()
    #     self.arg = arg
    pass

class Config(models.Model):
    """docstring for config."""
    #
    # def __init__(self, arg):
    #     super(config, self).__init__()
    #     self.arg = arg
    pass

bsys/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.forms import AuthenticationForm
from . import models as MD
from .models import User
from django.db import transaction


class BusCreationForm(forms.ModelForm):
    class Meta:
        model = MD.Bus
        fields = "__all__"
        widgets = {
                'lastCheckUp': forms.DateInput(format=('%m/%d/%Y'), attrs={'class':'form-control', 'placeholder':'Select a date', 'type':'date'}),
            }
            
class ToggleBusStatus(forms.ModelForm):
    class Meta:
        model = MD.Bus
        fields = ["status"]

class DriverSignUpForm(UserCreationForm):
    bus = forms.ModelChoiceField(MD.Bus.objects.all(),required=False,label="choose bus")
    def __init__(self, *args, **kwargs):
        super(DriverSignUpForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['placeholder'] = visible.field.label
    class Meta(UserCreationForm.Meta):
            model = User
            fields = [
                'username',
                "first_name",
                "last_name",
                "email",
            ]
    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_driver = True
        user.save()
        driver = MD.Driver.objects.create(user=user)
        return user

class DriverAuthForm(AuthenticationForm):
    def confirm_login_allowed(self, user):
        pass
    def __init__(self, *args, **kwargs):
        super(DriverAuthForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['placeholder'] = visible.field.label
    # role = forms.IntegerField(
    #     widget=forms.HiddenInput(),
    #     required = False,
    #     initial=1
    # )

class ManagerAuthForm(AuthenticationForm):
    def confirm_login_allowed(self, user):
        pass

    def __init__(self, *args, **kwargs):
        super(ManagerAuthForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['placeholder'] = visible.field.label
    # role = forms.IntegerField(
    #     widget=forms.HiddenInput(),
    #     required = False,
    #     initial=2
    # )
class ManagerCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(ManagerCreationForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['placeholder'] = visible.field.label
    class Meta(UserCreationForm.Meta):
        model = User
        fields = '__all__'
    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_admin = True
        user.save()
        driver = MD.Manager.objects.create(user=user)
        return user





# class ManagerUserChangeForm(UserChangeForm):
#
#     class Meta:
#         model = MD.Manager

bsys/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from . import forms as FM
from django.shortcuts import redirect
from django.views.generic import CreateView
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.template                import RequestContext
import logging
from .forms import DriverSignUpForm
from .models import User
from . import models as MD
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

logger = logging.getLogger(__name__)
# Create your views here.


def home(request):
    auth = False
    if request.user.is_authenticated:
        auth = True
    return render(request, 'home.html', {'auth':auth})

@login_required(login_url='/')
def profile(request):
    logger.warning(request.user.is_admin)
    logger.warning(request.user.is_driver)
    if request.user.is_admin:
        return render(request, 'profile/admin.html',{"drivers":MD.Driver.objects.all()})
    elif request.user.is_driver:
        driver_data = MD.Driver.objects.get(pk=request.user.id)
        form = FM.ToggleBusStatus()
        ## TODO: update driver profile view to show it's data
        ## TODO: create a form to allow driver to update bus status
        logger.warning(driver_data.bus)
        return render(request, 'profile/driver.html',{"driver":driver_data,"form":form})
    else:
        return redirect("/admin/")

class BusUpdate(UpdateView):
    model = MD.Bus
    fields = "__all__"
    template_name = "profile/BusEdit.html"
    success_url = reverse_lazy('bsys:BusList')

# from django.forms import inlineformset_factory
class DriverUpdate(UpdateView):
    model = MD.Driver
    # TODO: create a form class that exclude user / form that include user editable fields and use it as form_class
    fields = [
        "bus",
        "licenceNum"
    ]
    template_name = "profile/DriverEdit.html"
    success_url = reverse_lazy('bsys:DriverList')

class DriverUpdatePersonal(UpdateView):
    model = MD.User
    # user_formset = inlineformset_factory(MD.User,fields="first_name")
    fields = [
        "first_name",
        "last_name",
        "email",

    ]
    template_name = "profile/DriverPersonalEdit.html"
    success_url = reverse_lazy('bsys:DriverPersonalList')



def index(request):
    DrForm = FM.DriverAuthForm()
    AdForm = FM.ManagerAuthForm()
    if request.user.is_authenticated:
        return redirect('/profile/')
    if request.method == 'POST':
        logger.warning(str(request.POST['role']) == str(1))
        DrForm = FM.DriverAuthForm()
        AdForm = FM.ManagerAuthForm()
        if str(request.POST['role']) == str(1):
            form = FM.DriverAuthForm(data=request.POST)
        else:
            form = FM.ManagerAuthForm(data=request.POST)
        if form.is_valid():
            logger.warning("form validate")
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=raw_password)
            logger.warning(user.first_name)
            if user is not None:
                logger.warning("user not none")
                # user = authenticate(request,username=username, password=raw_password)
                login(request, user)
                return redirect("/profile/")
            else:
                logger.warning("form error")
        if str(request.POST['role']) == str(1):
            DrForm = form
        else:
            AdForm = form
    return render(request, 'index.html', {'AdForm': AdForm,"DrForm":DrForm})

@login_required(login_url='/')
def logout_view(request):
    logout(request)
    return redirect('/')

class DriverSignUpView(CreateView):
    model = User
    form_class = DriverSignUpForm
    template_name = 'signup.html'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('/profile/')


class DriverSignUpFormView(CreateView):
    model = User
    form_class = DriverSignUpForm
    template_name = 'profile/DriverCreate.html'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('/profile/d/create/')

@login_required(login_url='/')
def BusCreationFormView(request):
    if request.method == "POST":
        form = FM.BusCreationForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                # return redirect('/show')
            except:
                pass
    else:
        form = FM.BusCreationForm()
    return render(request,'profile/form_base.html',{'form':form,"form_id":"BusForm","form_title":"Bus Creation"})

class BusList(ListView):
    model = MD.Bus
    template_name = "profile/BusList.html"

class DriverList(ListView):
    model = MD.Driver
    template_name = "profile/DriverList.html"

class BusDeleteView(DeleteView):
    model = MD.Bus
    template_name="profile/BusDeleteConfirm.html"
    success_url = reverse_lazy('bsys:BusList')

class DriverDeleteView(DeleteView):
    model = MD.Driver
    template_name="profile/BusDeleteConfirm.html"
    success_url = reverse_lazy('bsys:DriverList')

@login_required(login_url='/')
def BusUpdateView(request, pk, template_name='profile/form_base.html'):
    Bus= get_object_or_404(MD.Bus, pk=pk)
    form = FM.BusCreationForm(request.POST or None, instance=MD.Bus)
    if form.is_valid():
        form.save()
        return redirect('/profile/b/update/?status=success')
    return render(request, template_name, {'form':form})

# def book_delete(request, pk, template_name='books/book_confirm_delete.html'):
#     book= get_object_or_404(Book, pk=pk)
#     if request.method=='POST':
#         book.delete()
#         return redirect('book_list')
#     return render(request, template_name, {'object':book})



def success_test(request):
    return render(request, 'st.html')

def faliur_test(request):
    return render(request, 'fl.html')


def sign_up(request):
    form = FM.DriverCreationForm()
    return render(request, 'signup.html',{'form': form,"type":"Driver"})

bsys/templates/fl.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1> faliur </h1>
  </body>
</html>

bsys/templates/home.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1> home page </h1>
    {% if auth %}
      <a href="{% url 'bsys:logout' %}">logout</a>
    {% endif %}
  </body>
</html>

bsys/templates/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <title>bsys</title>

  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <style>
  .login-container{
    margin-top: 5%;
    margin-bottom: 5%;
}
.login-form-1{
    padding: 5%;
    box-shadow: 0 5px 8px 0 rgba(0, 0, 0, 0.2), 0 9px 26px 0 rgba(0, 0, 0, 0.19);
}
.login-form-1 h3{
    text-align: center;
    color: #333;
}
.login-form-2{
    padding: 5%;
    background: #0062cc;
    box-shadow: 0 5px 8px 0 rgba(0, 0, 0, 0.2), 0 9px 26px 0 rgba(0, 0, 0, 0.19);
}
.login-form-2 h3{
    text-align: center;
    color: #fff;
}
.login-container form{
    padding: 10%;
}
.btnSubmit
{
    width: 50%;
    border-radius: 1rem;
    padding: 1.5%;
    border: none;
    cursor: pointer;
}
.login-form-1 .btnSubmit{
    font-weight: 600;
    color: #fff;
    background-color: #0062cc;
}
.login-form-2 .btnSubmit{
    font-weight: 600;
    color: #0062cc;
    background-color: #fff;
}
.login-form-2 .ForgetPwd{
    color: #fff;
    font-weight: 600;
    text-decoration: none;
}
.login-form-1 .ForgetPwd{
    color: #0062cc;
    font-weight: 600;
    text-decoration: none;
}

   </style>
</head>
<!-- Include the above in your HEAD tag -->
<body>
  <div class="container login-container">
    <div class="row">
      <div class="col-md-6 login-form-1">
        <h3>Admin Login</h3>
        <form method="post" novalidate>
            {% csrf_token %}

            {{ AdForm.non_field_errors }}

            {% for hidden_field in Adform.hidden_fields %}
              {{ hidden_field.errors }}
              {{ hidden_field }}
            {% endfor %}

            {% for field in AdForm.visible_fields %}

              <div class="form-group">
                {{ field }}

                {% for error in field.errors %}
                  <span>{{error}}</span>
                {% endfor %}
              </div>

            {% endfor %}
            <input type="hidden" name='role' value='2'/>

            <div class="form-group">
              <input type="submit" class="btnSubmit" value="Login" />
            </div>
            <!-- <div class="form-group">
              <a href="{% url 'bsys:signup' %}">Sign Up</a>
            </div> -->

          </form>
      </div>
      <div class="col-md-6 login-form-2">
        <h3>Driver Login</h3>
        <form method="post">
          {% csrf_token %}

          {{ DrForm.non_field_errors }}

          {% for hidden_field in Drform.hidden_fields %}
            {{ hidden_field.errors }}
            {{ hidden_field }}
          {% endfor %}

          {% for field in DrForm.visible_fields %}

            <div class="form-group">
              {{ field }}

              {% for error in field.errors %}
                <span>{{error}}</span>
              {% endfor %}
            </div>
          {% endfor %}
          <input type="hidden" name='role' value='1'/>
          <div class="form-group">
            <input type="submit"  class="btnSubmit" value="Login" />
          </div>
        </form>
      </div>
    </div>
  </div>
</body>
</html>
<head>

bsys/templates/signup.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <style>
      body, html, .bg-img {
          height: 100%;
          margin:0;
        }

        * {
          box-sizing: border-box;
        }

        .bg-img {
          /* The image used */
          background-image: url("https://www.hdcarwallpapers.com/walls/2016_mercedes_benz_future_bus-wide.jpg");

          /* Control the height of the image */
          min-height: 380px;

          /* Center and scale the image nicely */
          background-position: center;
          background-repeat: no-repeat;
          background-size: cover;
          position: relative;
        }

        /* Add styles to the form container */
        .container {
          position: absolute;
          right: 0;
          margin: 20px;
          max-width: 300px;
          padding: 16px;
          background-color: white;
        }

        /* Full-width input fields */

        /* Set a style for the submit button */
        .btn {
          background-color: #4CAF50;
          color: white;
          padding: 16px 20px;
          border: none;
          cursor: pointer;
          width: 100%;
          opacity: 0.9;
        }

        .btnSubmit
        {
            width: 50%;
            border-radius: 1rem;
            padding: 1.5%;
            border: none;
            cursor: pointer;
            background-color: #0062CC;
            color: #fff;
        }
        .btn:hover {
          opacity: 1;
        }
    </style>
  </head>
  <body>
    <div class="bg-img">
    <form method="post" novalidate class="container">
      <h1>Login {{ type }}</h1>
        {% csrf_token %}

        {{ form.non_field_errors }}

        {% for hidden_field in form.hidden_fields %}
          {{ hidden_field.errors }}
          {{ hidden_field }}
        {% endfor %}

        {% for field in form.visible_fields %}

          <div class="form-group">
            {{ field }}

            {% for error in field.errors %}
              <span>{{error}}</span>
            {% endfor %}
          </div>

        {% endfor %}
      <input type="submit" class="btnSubmit" value="Login"/>
    </form>
  </div>
  </body>
</html>

bsys/templates/st.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1> you succeded </h1>
  </body>
</html>