bsys/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

## TODO: add permissions to the crud form pages to prevent drivers from modifing other drivers/users data
app_name = 'bsys'
urlpatterns = [
    path("",views.index,name ='index'),
    path("home/",views.home,name ='home'),
    path('profile/b/delete/<int:pk>',login_required(views.BusDeleteView.as_view()), name='BusDelete'),
    path('profile/d/delete/<int:pk>', login_required(views.DriverDeleteView.as_view()), name='DriverDelete'),
    # path("signup/",views.sign_up,name ='signup'),
    path('profile/b/edit/<int:pk>', login_required(views.BusUpdate.as_view()), name='BusEdit'),
    path('profile/dp/edit/<int:pk>', login_required(views.DriverUpdatePersonal.as_view()), name='DriverPersonalEdit'),
    path('profile/d/edit/<int:pk>', login_required(views.DriverUpdate.as_view()), name='DriverEdit'),
    path('profile/b/list/', login_required(views.BusList.as_view()), name='BusList'),
    path('profile/d/list/', login_required(views.DriverList.as_view()), name='DriverList'),
    path('signup/', login_required(views.DriverSignUpView.as_view()), name='signup'),
    path("success/",views.success_test,name ='success'),
    path("faliur/",views.faliur_test,name ='faliur'),
    path("logout/",views.logout_view,name="logout"),
    path("profile/",views.profile,name="profile"),
    path('profile/d/create/', login_required(views.DriverSignUpFormView.as_view()), name='driverCreate'),
    path('profile/b/create/', views.BusCreationFormView, name='BusCreate'),
    path('profile/b/update/', views.BusUpdateView, name='BusUpdate'),
]

bus_system/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

bsys/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser , BaseUserManager
# from django.contrib.auth.models import User
from django.db import transaction

# Create your models here.

# class CustomUser(AbstractUser):
#     pass

# class Role(models.Model):
#     ROLE_CHOICES = (
#         (1, 'Driver'),
#         (2, 'Admin'),
#     )
#     # id = models.IntegerField(primary_key=True)
#     name = models.CharField(choices=ROLE_CHOICES,max_length=12)
#     def __str__(self):
#         return self.get_id_display()

class User(AbstractUser):
    # roles = models.ForeignKey(
    #     'Role',
    #     on_delete=models.CASCADE,
    #     # null= True
    # )
    is_admin = models.BooleanField("admin status",default=False)
    is_driver = models.BooleanField("driver status",default=False)
    salary = models.FloatField("salary",default=2000)


class Manager(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    def __init__(self, *args, **kwargs):
        # self._meta.   get_field('is_admin').default = True
        super(Manager, self).__init__(*args, **kwargs)


class Bus(models.Model):
    """docstring for ."""
    licenceCode = models.CharField(max_length=20,null=True)
    status = models.BooleanField("status",default=False)
    lastCheckUp = models.DateField(null=True)
    def __str__(self):
        return self.licenceCode

class Driver(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    bus = models.OneToOneField(Bus ,null=True,on_delete=models.SET_NULL)
    licenceNum = models.CharField(max_length=20,null=True)
    def __str__(self):
        return self.user.first_name
    def __init__(self, *args, **kwargs):
        # self._meta.get_field('is_driver').default = True
        super(Driver, self).__init__(*args, **kwargs)

class RoadLines(models.Model):
    """docstring for ."""

    # def __init__(self, arg):
    #     super(, self).__init__()
    #     self.arg = arg
    pass

class StopStations(models.Model):
    pass

class Areas(models.Model):
    """docstring for areas."""

    # def __init__(self, arg):
    #     super(areas, self).__init__()
    #     self.arg = arg
    pass

class Config(models.Model):
    """docstring for config."""
    #
    # def __init__(self, arg):
    #     super(config, self).__init__()
    #     self.arg = arg
    pass

bsys/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.forms import AuthenticationForm
from . import models as MD
from .models import User
from django.db import transaction


class BusCreationForm(forms.ModelForm):
    class Meta:
        model = MD.Bus
        fields = "__all__"
        widgets = {
                'lastCheckUp': forms.DateInput(format=('%m/%d/%Y'), attrs={'class':'form-control', 'placeholder':'Select a date', 'type':'date'}),
            }
            
class ToggleBusStatus(forms.ModelForm):
    class Meta:
        model = MD.Bus
        fields = ["status"]

class DriverSignUpForm(UserCreationForm):
    bus = forms.ModelChoiceField(MD.Bus.objects.all(),required=False,label="choose bus")
    def __init__(self, *args, **kwargs):
        super(DriverSignUpForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['placeholder'] = visible.field.label
    class Meta(UserCreationForm.Meta):
            model = User
            fields = [
                'username',
                "first_name",
                "last_name",
                "email",
            ]
    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_driver = True
        user.save()
        driver = MD.Driver.objects.create(user=user)
        return user

class DriverAuthForm(AuthenticationForm):
    def confirm_login_allowed(self, user):
        pass
    def __init__(self, *args, **kwargs):
        super(DriverAuthForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['placeholder'] = visible.field.label
    # role = forms.IntegerField(
    #     widget=forms.HiddenInput(),
    #     required = False,
    #     initial=1
    # )

class ManagerAuthForm(AuthenticationForm):
    def confirm_login_allowed(self, user):
        pass

    def __init__(self, *args, **kwargs):
        super(ManagerAuthForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['placeholder'] = visible.field.label
    # role = forms.IntegerField(
    #     widget=forms.HiddenInput(),
    #     required = False,
    #     initial=2
    # )
class ManagerCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(ManagerCreationForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['placeholder'] = visible.field.label
    class Meta(UserCreationForm.Meta):
        model = User
        fields = '__all__'
    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_admin = True
        user.save()
        driver = MD.Manager.objects.create(user=user)
        return user





# class ManagerUserChangeForm(UserChangeForm):
#
#     class Meta:
#         model = MD.Manager

bsys/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from . import forms as FM
from django.shortcuts import redirect
from django.views.generic import CreateView
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.template                import RequestContext
import logging
from .forms import DriverSignUpForm
from .models import User
from . import models as MD
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

logger = logging.getLogger(__name__)
# Create your views here.


def home(request):
    auth = False
    if request.user.is_authenticated:
        auth = True
    return render(request, 'home.html', {'auth':auth})

@login_required(login_url='/')
def profile(request):
    logger.warning(request.user.is_admin)
    logger.warning(request.user.is_driver)
    if request.user.is_admin:
        return render(request, 'profile/admin.html',{"drivers":MD.Driver.objects.all()})
    elif request.user.is_driver:
        driver_data = MD.Driver.objects.get(pk=request.user.id)
        form = FM.ToggleBusStatus()
        ## TODO: update driver profile view to show it's data
        ## TODO: create a form to allow driver to update bus status
        logger.warning(driver_data.bus)
        return render(request, 'profile/driver.html',{"driver":driver_data,"form":form})
    else:
        return redirect("/admin/")

class BusUpdate(UpdateView):
    model = MD.Bus
    fields = "__all__"
    template_name = "profile/BusEdit.html"
    success_url = reverse_lazy('bsys:BusList')

# from django.forms import inlineformset_factory
class DriverUpdate(UpdateView):
    model = MD.Driver
    # TODO: create a form class that exclude user / form that include user editable fields and use it as form_class
    fields = [
        "bus",
        "licenceNum"
    ]
    template_name = "profile/DriverEdit.html"
    success_url = reverse_lazy('bsys:DriverList')

class DriverUpdatePersonal(UpdateView):
    model = MD.User
    # user_formset = inlineformset_factory(MD.User,fields="first_name")
    fields = [
        "first_name",
        "last_name",
        "email",

    ]
    template_name = "profile/DriverPersonalEdit.html"
    success_url = reverse_lazy('bsys:DriverPersonalList')



def index(request):
    DrForm = FM.DriverAuthForm()
    AdForm = FM.ManagerAuthForm()
    if request.user.is_authenticated:
        return redirect('/profile/')
    if request.method == 'POST':
        logger.warning(str(request.POST['role']) == str(1))
        DrForm = FM.DriverAuthForm()
        AdForm = FM.ManagerAuthForm()
        if str(request.POST['role']) == str(1):
            form = FM.DriverAuthForm(data=request.POST)
        else:
            form = FM.ManagerAuthForm(data=request.POST)
        if form.is_valid():
            logger.warning("form validate")
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=raw_password)
            logger.warning(user.first_name)
            if user is not None:
                logger.warning("user not none")
                # user = authenticate(request,username=username, password=raw_password)
                login(request, user)
                return redirect("/profile/")
            else:
                logger.warning("form error")
        if str(request.POST['role']) == str(1):
            DrForm = form
        else:
            AdForm = form
    return render(request, 'index.html', {'AdForm': AdForm,"DrForm":DrForm})

@login_required(login_url='/')
def logout_view(request):
    logout(request)
    return redirect('/')

class DriverSignUpView(CreateView):
    model = User
    form_class = DriverSignUpForm
    template_name = 'signup.html'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('/profile/')


class DriverSignUpFormView(CreateView):
    model = User
    form_class = DriverSignUpForm
    template_name = 'profile/DriverCreate.html'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('/profile/d/create/')

@login_required(login_url='/')
def BusCreationFormView(request):
    if request.method == "POST":
        form = FM.BusCreationForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                # return redirect('/show')
            except:
                pass
    else:
        form = FM.BusCreationForm()
    return render(request,'profile/form_base.html',{'form':form,"form_id":"BusForm","form_title":"Bus Creation"})

class BusList(ListView):
    model = MD.Bus
    template_name = "profile/BusList.html"

class DriverList(ListView):
    model = MD.Driver
    template_name = "profile/DriverList.html"

class BusDeleteView(DeleteView):
    model = MD.Bus
    template_name="profile/BusDeleteConfirm.html"
    success_url = reverse_lazy('bsys:BusList')

class DriverDeleteView(DeleteView):
    model = MD.Driver
    template_name="profile/BusDeleteConfirm.html"
    success_url = reverse_lazy('bsys:DriverList')

@login_required(login_url='/')
def BusUpdateView(request, pk, template_name='profile/form_base.html'):
    Bus= get_object_or_404(MD.Bus, pk=pk)
    form = FM.BusCreationForm(request.POST or None, instance=MD.Bus)
    if form.is_valid():
        form.save()
        return redirect('/profile/b/update/?status=success')
    return render(request, template_name, {'form':form})

# def book_delete(request, pk, template_name='books/book_confirm_delete.html'):
#     book= get_object_or_404(Book, pk=pk)
#     if request.method=='POST':
#         book.delete()
#         return redirect('book_list')
#     return render(request, template_name, {'object':book})



def success_test(request):
    return render(request, 'st.html')

def faliur_test(request):
    return render(request, 'fl.html')


def sign_up(request):
    form = FM.DriverCreationForm()
    return render(request, 'signup.html',{'form': form,"type":"Driver"})

bsys/templates/profile/BusCreate.html
{% extends "profile/base_profile.html" %}
{% load static %}

{% block content %}
<div class="animated fadeIn">
    <div class="row">
      <div class="col-lg-6">
            <div class="card">
                <div class="card-header">
                    <strong>Bus Form</strong>
                </div>
                <div class="card-body card-block">
                    <form id="busForm" method="post" enctype="multipart/form-data" class="form-horizontal">
                      {% csrf_token %}

                      {{ form.non_field_errors }}

                      {% for hidden_field in form.hidden_fields %}
                        {{ hidden_field.errors }}
                        {{ hidden_field }}
                      {% endfor %}

                      {% for field in form.visible_fields %}

                        <div class="row form-group">
                          <div class="col col-md-3"><label class=" form-control-label">{{field.label}}</label></div>

                            {{ field }}

                          {% for error in field.errors %}
                            <span>{{error}}</span>
                          {% endfor %}

                        </div>





                      {% endfor %}
                        <!-- <div class="row form-group">
                            <div class="col col-md-3"><label for="file-multiple-input" class=" form-control-label">Multiple File input</label></div>
                            <div class="col-12 col-md-9"><input type="file" id="file-multiple-input" name="file-multiple-input" multiple="" class="form-control-file"></div>
                        </div> -->
                    </form>
                </div>
                <div class="card-footer">
                    <button type="submit" form="busForm" class="btn btn-primary btn-sm">
                        <i class="fa fa-dot-circle-o"></i> Submit
                    </button>
                    <button type="reset"form="busForm"  class="btn btn-danger btn-sm">
                        <i class="fa fa-ban"></i> Reset
                    </button>
                </div>
            </div>
        </div>
    </div>
    <!-- <form method="post" novalidate class="container">
      <input type="submit" class="btnSubmit" value="Login"/>
    </form> -->
</div>
{% endblock %}

bsys/templates/profile/BusDeleteConfirm.html
{% extends "profile/base_profile.html" %}
{% load static %}

{% block content %}
<div class="animated fadeIn">
    <div class="row">
      <div class="col-lg-6">
            <div class="card">
                <div class="card-header">
                    <strong>{{ form_title }}</strong>
                </div>
                <div class="card-body card-block">
                    <form id="del_con" method="post" enctype="multipart/form-data" class="form-horizontal">
                      <form method="post">{% csrf_token %}
                          <p>Are you sure you want to delete "{{ object }}"?</p>
                    </form>
                </div>
                <div class="card-footer">
                    <button type="submit" form="del_con" value="Confirm" class="btn btn-primary btn-sm">
                        <i class="fa fa-dot-circle-o"></i> Confirm
                    </button>
                    <!-- <button type="reset"form="del_con"  class="btn btn-danger btn-sm">
                        <i class="fa fa-ban"></i> Reset
                    </button> -->
                </div>
            </div>
        </div>
    </div>
    <!-- <form method="post" novalidate class="container">
      <input type="submit" class="btnSubmit" value="Login"/>
    </form> -->
</div>
{% endblock %}

bsys/templates/profile/BusEdit.html
{% extends "profile/base_profile.html" %}
{% load static %}

{% block content %}
<div class="animated fadeIn">
    <div class="row">
      <div class="col-lg-6">
            <div class="card">
                <div class="card-header">
                    <strong>Bus Form</strong>
                </div>
                <div class="card-body card-block">
                    <form id="busForm" method="post" enctype="multipart/form-data" class="form-horizontal">
                      {% csrf_token %}

                      {{ form.non_field_errors }}

                      {% for hidden_field in form.hidden_fields %}
                        {{ hidden_field.errors }}
                        {{ hidden_field }}
                      {% endfor %}

                      {% for field in form.visible_fields %}

                        <div class="row form-group">
                          <div class="col col-md-3"><label class=" form-control-label">{{field.label}}</label></div>

                            {{ field }}

                          {% for error in field.errors %}
                            <span>{{error}}</span>
                          {% endfor %}

                        </div>





                      {% endfor %}
                        <!-- <div class="row form-group">
                            <div class="col col-md-3"><label for="file-multiple-input" class=" form-control-label">Multiple File input</label></div>
                            <div class="col-12 col-md-9"><input type="file" id="file-multiple-input" name="file-multiple-input" multiple="" class="form-control-file"></div>
                        </div> -->
                    </form>
                </div>
                <div class="card-footer">
                    <button type="submit" form="busForm" class="btn btn-primary btn-sm">
                        <i class="fa fa-dot-circle-o"></i> Submit
                    </button>
                    <button type="reset"form="busForm"  class="btn btn-danger btn-sm">
                        <i class="fa fa-ban"></i> Reset
                    </button>
                </div>
            </div>
        </div>
    </div>
    <!-- <form method="post" novalidate class="container">
      <input type="submit" class="btnSubmit" value="Login"/>
    </form> -->
</div>
{% endblock %}

bsys/templates/profile/BusList.html
{% extends "profile/base_profile.html" %}
{% load static %}

{% block content %}
<h1>buses</h1>

<table border="1">
<thead>
    <tr>
    <th>licence Code</th>
    <th>lastCheck Up</th>
    <!-- <th>View</th> -->
    <th>Edit</th>
    <th>Delete</th>
    </tr>
</thead>
<tbody>
    {% for bus in object_list %}
    <tr>
      <td>{{ bus.licenceCode }}</td>
      <td>{{ bus.lastCheckUp }}</td>
      <!-- <td><a href="#">Edit</a></td> -->
      <td><a href="{% url "bsys:BusEdit" bus.id %}">Edit</a></td>
      <td><a href="{% url "bsys:BusDelete" bus.id %}">delete</a></td>

    </tr>
    {% endfor %}
</tbody>
</table>

{% endblock %}

bsys/templates/profile/DriverCreate.html
{% extends "profile/base_profile.html" %}
{% load static %}


{% block content %}
<div class="animated fadeIn">
    <div class="row">
      <div class="col-lg-6">
            <div class="card">
                <div class="card-header">
                    <strong>Driver Creation</strong>
                </div>
                <div class="card-body card-block">
                    <form id="driverCreate" method="post" enctype="multipart/form-data" class="form-horizontal">
                      {% csrf_token %}

                      {{ form.non_field_errors }}

                      {% for hidden_field in form.hidden_fields %}
                        {{ hidden_field.errors }}
                        {{ hidden_field }}
                      {% endfor %}

                      {% for field in form.visible_fields %}

                        <div class="row form-group">
                          <div class="col col-md-3"><label class=" form-control-label">{{field.label}}</label></div>

                            {{ field }}

                          {% for error in field.errors %}
                            <span>{{error}}</span>
                          {% endfor %}

                        </div>





                      {% endfor %}
                        <!-- <div class="row form-group">
                            <div class="col col-md-3"><label for="file-multiple-input" class=" form-control-label">Multiple File input</label></div>
                            <div class="col-12 col-md-9"><input type="file" id="file-multiple-input" name="file-multiple-input" multiple="" class="form-control-file"></div>
                        </div> -->
                    </form>
                </div>
                <div class="card-footer">
                    <button type="submit" form="driverCreate" class="btn btn-primary btn-sm">
                        <i class="fa fa-dot-circle-o"></i> Submit
                    </button>
                    <button type="reset"form="driverCreate"  class="btn btn-danger btn-sm">
                        <i class="fa fa-ban"></i> Reset
                    </button>
                </div>
            </div>
        </div>
    </div>
    <!-- <form method="post" novalidate class="container">
      <input type="submit" class="btnSubmit" value="Login"/>
    </form> -->
</div>
{% endblock %}

bsys/templates/profile/DriverDeleteConfirm.html
{% extends "profile/base_profile.html" %}
{% load static %}

{% block content %}
<div class="animated fadeIn">
    <div class="row">
      <div class="col-lg-6">
            <div class="card">
                <div class="card-header">
                    <strong>{{ form_title }}</strong>
                </div>
                <div class="card-body card-block">
                    <form id="del_con" method="post" enctype="multipart/form-data" class="form-horizontal">
                      <form method="post">{% csrf_token %}
                          <p>Are you sure you want to delete "{{ object }}"?</p>
                    </form>
                </div>
                <div class="card-footer">
                    <button type="submit" form="del_con" value="Confirm" class="btn btn-primary btn-sm">
                        <i class="fa fa-dot-circle-o"></i> Confirm
                    </button>
                    <!-- <button type="reset"form="del_con"  class="btn btn-danger btn-sm">
                        <i class="fa fa-ban"></i> Reset
                    </button> -->
                </div>
            </div>
        </div>
    </div>
    <!-- <form method="post" novalidate class="container">
      <input type="submit" class="btnSubmit" value="Login"/>
    </form> -->
</div>
{% endblock %}

bsys/templates/profile/DriverEdit.html
{% extends "profile/base_profile.html" %}
{% load static %}


{% block content %}
<div class="animated fadeIn">
    <div class="row">
      <div class="col-lg-6">
            <div class="card">
                <div class="card-header">
                    <strong>Driver Creation</strong>
                </div>
                <div class="card-body card-block">
                    <form id="driverCreate" method="post" enctype="multipart/form-data" class="form-horizontal">
                      {% csrf_token %}

                      {{ form.non_field_errors }}

                      {% for hidden_field in form.hidden_fields %}
                        {{ hidden_field.errors }}
                        {{ hidden_field }}
                      {% endfor %}

                      {% for field in form.visible_fields %}

                        <div class="row form-group">
                          <div class="col col-md-3"><label class=" form-control-label">{{field.label}}</label></div>

                            {{ field }}

                          {% for error in field.errors %}
                            <span>{{error}}</span>
                          {% endfor %}

                        </div>





                      {% endfor %}
                        <!-- <div class="row form-group">
                            <div class="col col-md-3"><label for="file-multiple-input" class=" form-control-label">Multiple File input</label></div>
                            <div class="col-12 col-md-9"><input type="file" id="file-multiple-input" name="file-multiple-input" multiple="" class="form-control-file"></div>
                        </div> -->
                    </form>
                </div>
                <div class="card-footer">
                    <button type="submit" form="driverCreate" class="btn btn-primary btn-sm">
                        <i class="fa fa-dot-circle-o"></i> Submit
                    </button>
                    <button type="reset"form="driverCreate"  class="btn btn-danger btn-sm">
                        <i class="fa fa-ban"></i> Reset
                    </button>
                </div>
            </div>
        </div>
    </div>
    <!-- <form method="post" novalidate class="container">
      <input type="submit" class="btnSubmit" value="Login"/>
    </form> -->
</div>
{% endblock %}

bsys/templates/profile/DriverList.html
{% extends "profile/base_profile.html" %}
{% load static %}

{% block content %}
<h1>drivers</h1>

<table border="1">
<thead>
    <tr>
    <th>UserName</th>
    <th>Bus</th>
    <th>licence Code</th>
    <!-- <th>View</th> -->
    <th>Edit driver specific data</th>
    <th>Edit driver personal data</th>
    <th>Delete</th>
    </tr>
</thead>
<tbody>
    {% for driver in object_list %}
    <tr>
      <td>{{ driver.user }}</td>
      <td>{{ driver.bus }}</td>
      <td>{{ driver.licenceNum }}</td>
      <td><a href="{% url "bsys:DriverEdit" driver.user.id %}">Edit</a></td>
      <td><a href="{% url "bsys:DriverPersonalEdit" driver.user.id %}">Edit</a></td>
      <td><a href="{% url "bsys:DriverDelete" driver.user.id %}">delete</a></td>

    </tr>
    {% endfor %}
</tbody>
</table>

{% endblock %}

bsys/templates/profile/DriverPersonalEdit.html
{% extends "profile/base_profile.html" %}
{% load static %}


{% block content %}
<div class="animated fadeIn">
    <div class="row">
      <div class="col-lg-6">
            <div class="card">
                <div class="card-header">
                    <strong>Driver Creation</strong>
                </div>
                <div class="card-body card-block">
                    <form id="driverCreate" method="post" enctype="multipart/form-data" class="form-horizontal">
                      {% csrf_token %}

                      {{ form.non_field_errors }}

                      {% for hidden_field in form.hidden_fields %}
                        {{ hidden_field.errors }}
                        {{ hidden_field }}
                      {% endfor %}

                      {% for field in form.visible_fields %}

                        <div class="row form-group">
                          <div class="col col-md-3"><label class=" form-control-label">{{field.label}}</label></div>

                            {{ field }}

                          {% for error in field.errors %}
                            <span>{{error}}</span>
                          {% endfor %}

                        </div>





                      {% endfor %}
                        <!-- <div class="row form-group">
                            <div class="col col-md-3"><label for="file-multiple-input" class=" form-control-label">Multiple File input</label></div>
                            <div class="col-12 col-md-9"><input type="file" id="file-multiple-input" name="file-multiple-input" multiple="" class="form-control-file"></div>
                        </div> -->
                    </form>
                </div>
                <div class="card-footer">
                    <button type="submit" form="driverCreate" class="btn btn-primary btn-sm">
                        <i class="fa fa-dot-circle-o"></i> Submit
                    </button>
                    <button type="reset"form="driverCreate"  class="btn btn-danger btn-sm">
                        <i class="fa fa-ban"></i> Reset
                    </button>
                </div>
            </div>
        </div>
    </div>
    <!-- <form method="post" novalidate class="container">
      <input type="submit" class="btnSubmit" value="Login"/>
    </form> -->
</div>
{% endblock %}

bsys/templates/profile/driver.html
{% extends "profile/base_profile.html" %}
{% load static %}


{% block content %}
<!-- Animated -->
<div class="animated fadeIn">
  <table style="width:100%">
    <tr>
      <th>Name</th>
      <td>{{request.user.first_name}} {{request.user.last_name}}</td>
    </tr>
    <tr>
      <th>Bus</th>
      <td>{% if driver.bus is not None %} {{driver.bus}} {% else %}  N/A {% endif %}</td>
    </tr>
    {% if driver.bus is not None %}
    <tr>
      <!-- TODO: connect the form with ajax onchange  -->
      <th>bus status</th>
      <td><form method=post>{% csrf_token %}{{form.as_p}}</form></td>
    </tr>
    {% endif %}
  </table>
</div>
<!-- .animated -->
{% endblock %}